# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cashboard}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Subimage LLC"]
  s.date = %q{2010-07-29}
  s.description = %q{For more information see the homepage. Support and discussion can be found on the Cashboard forum (http://forum.getcashboard.com/)}
  s.email = %q{support@getcashboard.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    ".autotest",
     ".gitignore",
     "LICENSE",
     "README.textile",
     "Rakefile",
     "examples/create_account.rb",
     "examples/list_stuff_in_account.rb",
     "examples/simple_workflow.rb",
     "examples/time_tracking.rb",
     "examples/toggle_timer.rb",
     "lib/cashboard.rb",
     "lib/cashboard/account.rb",
     "lib/cashboard/base.rb",
     "lib/cashboard/behaviors/base.rb",
     "lib/cashboard/behaviors/lists_line_items.rb",
     "lib/cashboard/behaviors/toggleable.rb",
     "lib/cashboard/client_company.rb",
     "lib/cashboard/client_contact.rb",
     "lib/cashboard/company_membership.rb",
     "lib/cashboard/document_template.rb",
     "lib/cashboard/employee.rb",
     "lib/cashboard/errors.rb",
     "lib/cashboard/estimate.rb",
     "lib/cashboard/expense.rb",
     "lib/cashboard/invoice.rb",
     "lib/cashboard/invoice_line_item.rb",
     "lib/cashboard/invoice_payment.rb",
     "lib/cashboard/line_item.rb",
     "lib/cashboard/payment.rb",
     "lib/cashboard/project.rb",
     "lib/cashboard/project_assignment.rb",
     "lib/cashboard/time_entry.rb",
     "lib/cashboard/version.rb",
     "lib/typecasted_open_struct.rb",
     "test/fixtures/account.xml",
     "test/fixtures/cashboard_credentials.yml",
     "test/fixtures/client_companies.xml",
     "test/fixtures/client_contacts.xml",
     "test/fixtures/company_memberships.xml",
     "test/fixtures/document_templates.xml",
     "test/fixtures/employees.xml",
     "test/fixtures/estimates.xml",
     "test/fixtures/expenses.xml",
     "test/fixtures/invoice_line_items.xml",
     "test/fixtures/invoice_payments.xml",
     "test/fixtures/invoices.xml",
     "test/fixtures/line_items.xml",
     "test/fixtures/payments.xml",
     "test/fixtures/project_assignments.xml",
     "test/fixtures/projects.xml",
     "test/fixtures/time_entries.xml",
     "test/full.rb",
     "test/test_helper.rb",
     "test/unit/account_test.rb",
     "test/unit/document_template_test.rb",
     "test/unit/estimate_test.rb",
     "test/unit/expense_test.rb",
     "test/unit/invoice_test.rb",
     "test/unit/project_test.rb",
     "test/unit/time_entry_test.rb"
  ]
  s.homepage = %q{http://github.com/subimage/cashboard-rb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby wrapper library for the Cashboard API}
  s.test_files = [
    "test/full.rb",
     "test/test_helper.rb",
     "test/unit/account_test.rb",
     "test/unit/document_template_test.rb",
     "test/unit/estimate_test.rb",
     "test/unit/expense_test.rb",
     "test/unit/invoice_test.rb",
     "test/unit/project_test.rb",
     "test/unit/time_entry_test.rb",
     "examples/create_account.rb",
     "examples/list_stuff_in_account.rb",
     "examples/simple_workflow.rb",
     "examples/time_tracking.rb",
     "examples/toggle_timer.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_runtime_dependency(%q<httparty>, [">= 0.6.1"])
      s.add_runtime_dependency(%q<xml-simple>, [">= 1.0.12"])
      s.add_development_dependency(%q<mocha>, [">= 0.9.8"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.8"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_dependency(%q<httparty>, [">= 0.6.1"])
      s.add_dependency(%q<xml-simple>, [">= 1.0.12"])
      s.add_dependency(%q<mocha>, [">= 0.9.8"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.3.5"])
    s.add_dependency(%q<httparty>, [">= 0.6.1"])
    s.add_dependency(%q<xml-simple>, [">= 1.0.12"])
    s.add_dependency(%q<mocha>, [">= 0.9.8"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
  end
end

